[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"
[".config/tmux/plugins/catppuccin/tmux"]
    type = "git-repo"
    url = "https://github.com/catppuccin/tmux.git"
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/alapins/LazyVimStarter"
    refreshPeriod = "168h"
